baseURL = "http://example.org/"
languageCode = "en-us"
title = "Unicorn"

[params]

    [[params.manifesto]]
      title = "Career Focused"
      svg = "rocket.svg"
      sub = "Local and regional employers and industry leaders are involved in your education.  Our curriculum is specially tailored to real needs in the job sector, and build blah blah "

    [[params.manifesto]]
      title = "Think In Code"
      svg = "compy.svg"
      sub = "You will learn to build your ideas with code"


    [[params.manifesto]]
      title = "Learn by doing"
      svg = "people.svg"
      sub = "You will learn to build your ideas with code"



    [[params.companies]]
    name = "Avista"
    logo = "avista.png"

    [[params.companies]]
    name = "CyberCoders"
    logo = "cyber_coders.png"

    [[params.companies]]
    name = "Ecova"
    logo = "ecova.png"

    [[params.companies]]
    name = "F5"
    logo = "f5.png"

    [[params.companies]]
    name = "Imprezzio"
    logo = "imprezzio.png"

    [[params.companies]]
    name = "Next IT"
    logo = "next_it.png"


    [[params.courses]]
    name = "Web Development"
    logo = "web_dev.svg"
    desc = "Learn to build robust, beautiful, interactive web applications.  This course focuses on the contemporary skills needed for a career in web development today."
    status = "closed"

    [[params.courses]]
    name = "Full Stack Foundations"
    logo = "full_stack.svg"
    desc = "Learn to build robust, beautiful, interactive web applications.  This course focuses on the contemporary skills needed for a career in web development today."
    status = "closed"