baseURL = "http://example.org/"
languageCode = "en-us"
title = "Unicorn"

[params]
    [[params.facts]]
      big = "$84.5K"
      icon = "ic_attach_money_white_24px.svg"
      sub = "Average Salary"
      explanation = "At the end of 2017, the average salary for software developers in Spokane County was $84,353.  This figure varies from region to region, and for Washington State in general the average salary was $133,194."

    [[params.facts]]
      big = "22,000"
      icon = "ic_trending_up_white_24px.svg"
      sub = "New Software Jobs"
      explanation = "Software development is one of the largest employment sectors in Washington State, with over 75,000 currently working.  State-level forecasts predict an average growth rate of 4.2% in the near term, with over 20,000 new jobs being added."

    [[params.facts]]
      big = "92%"
      icon = "ic_important_devices_white_24px.svg"
      sub = "Most Demanded Skill"
      explanation = "In Washington State 21 of the 25 most common in-demand skills in the state are related to software development.  Learning to write code is the most valuable skill today."
    


    [[params.manifesto]]
      title = "Career Focused"
      svg = "ic_school_white_24px.svg"
      sub = "Local employers and industry leaders are involved in your education.  Our curriculum is specially tailored to real demand in Spokane and the Inland Northwest. Join an expansive network of professionals and personalized career services"

    [[params.manifesto]]
      title = "Flexible Schedule"
      svg = "ic_free_breakfast_white_24px.svg"
      sub = "Your time is important.  That's why we offer options.  You have the choice to take your education in the fast-lane with full-time all-day sessions, or gain the same skills through evening part-time courses."


    [[params.manifesto]]
      title = "Real-World Skills"
      svg = "ic_dvr_white_24px.svg"
      sub = "Coding is a craft, not a science.  Your education will be about making amazing things and realizing your ideas.  You will build up your portfolio of real projects & and demonstrable skills."



    [[params.companies]]
    name = "Avista"
    logo = "avista.png"

    [[params.companies]]
    name = "CyberCoders"
    logo = "cyber_coders.png"

    [[params.companies]]
    name = "Ecova"
    logo = "ecova.png"

    [[params.companies]]
    name = "F5"
    logo = "f5.png"

    [[params.companies]]
    name = "Imprezzio"
    logo = "imprezzio.png"

    [[params.companies]]
    name = "Next IT"
    logo = "next_it.png"
